gtkwave/gtkwave

gtkwave3-gtk3/src/helpers/fst/fastlz.c, gtkwave3-gtk3/src/helpers/fst/fstapi.c, gtkwave3-gtk3/src/wavealloca.h, gtkwave3/src/helpers/fst/fastlz.c, gtkwave3/src/helpers/fst/fstapi.c
This fixes:
- Inconsistency in wavealloc.h between versions breaking MSC.
- GCC unused variable warning
- Adds ifdef so Verilator can have identical files
Thanks for the git repo, I'm privileged to send your first "pull request"!  Let me know if there's any issues.  If it looks good you can just accept the pull request (I suggest the "squash" option) and github will do the rest. Otherwise:  https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/merging-a-pull-request
=> Allow overriding config.h and fix compiler issues.

gtkwave3-gtk3/ChangeLog, gtkwave3-gtk3/src/ghw.c, gtkwave3-gtk3/src/ghwlib.c, gtkwave3-gtk3/src/ghwlib.h, gtkwave3/ChangeLog, gtkwave3/src/ghw.c, gtkwave3/src/ghwlib.c, gtkwave3/src/ghwlib.h
To handle unbounded arrays and records.
The file format is backward compatible but new types have been added for vhdl 2008
=> ghw: resync ghwlib and adjust ghw.c

gtkwave3-gtk3/src/helpers/fst/fstapi.c, gtkwave3/src/helpers/fst/fstapi.c
Address sanitizer told me that `xc->xc_parent` is referred after `free(xc)`.
=> Fix use-after-free of xc. No functional change is intended.

.github/workflows/build.yml, MSYS2/gtk2/PKGBUILD, MSYS2/gtk3/PKGBUILD
CI was failing because package `tklib-git` is not available anymore. It's now `tklib`. That's fixed in this PR. At the same time, due to the arbitrary compiler crashes, each build is retried three times.
=> ci: fix MSYS2 recipes, try 3 times

gtkwave3/src/helpers/fst/CMakeLists.txt, gtkwave3/src/helpers/fst/fst_win_unistd.h, gtkwave3/src/helpers/fst/fstapi.c, gtkwave3/src/helpers/fst/fstapi.h
GtkWave does not support Visual Studio builds, but MSYS2 builds work well on Windows.
However it may be useful to integrate FST waveform dumps into simulators developed with Visual Studio.
It mostly works out-of-the box. The only issue I had to debug is waveforms get corrupted
when size of FST grows larger than 2.1 GB. It turned out off_t is 32bit on Windows.
Replaced it with int64_t to have consistent behavior with Windows and Linux builds.
=> Support building fstapi using Microsoft MSVC compiler

gtkwave3-gtk3/src/helpers/fst/fst_win_unistd.h, gtkwave3/src/helpers/fst/fst_win_unistd.h
This adds a copyright to the (relatively) new header file, as it was missing one.  This file is used by Verilator, and we try to ensure every file has a copyright.
Thanks
=> Add copyright to new file.

gtkwave3-gtk3/src/wavewindow.c
This PR improves the drawing of filled waveforms. The current code doesn't correctly align the filled rectangle with the pixel grid, which causes some blurring at the edges. This is especially noticeable in black and white mode.
Before (UI scaling: 1, scaled 4x in GIMP)
After:
I've also changed the line cap to square, which removes some gaps in the display and results in a crisper display:
Before (UI scaling: 3):
After:
=> Improve drawing of filled waveforms

gtkwave3-gtk3/src/main.c, gtkwave3-gtk3/src/treesearch.c
This PR replaces the regular GtkEntry in the SST sidebar with a GtkSearchEntry. The search entry contains a search icon, which makes the "Filter:" label redundant. By removing the label and the frame around the buttons the UI looks cleaner.
If you think that PRs like this are useful I would like to continue to tweak the UI/UX in further PRs. But this is made harder by having to maintain the backward compatibility with GTK 2. Do you plan to remove the GTK 2 support from "gtkwave3-gtk3" at some point?
There are two functions which build a similar SST widget: `treebox` and `treeboxframe`. Is the separate `treebox` window still accessible in the GTK3 version? I've only modified `treeboxframe` in this PR.
Before:
After:
=> Use GtkSearchEntry in SST

gtkwave3-gtk3/src/entry.c, gtkwave3-gtk3/src/globals.c, gtkwave3-gtk3/src/globals.h, gtkwave3-gtk3/src/signalwindow.c
This PR changes the implementation of `entrybox` to use a GTK dialog instead of a regular window.
I might have missed the reason `entrybox` was implemented this way, but using a dialog seems easier because it can be made modal without any additional code. The dialog is now also correctly positioned and the parent window gets dimmed to indicate that it is disabled.
Before:
After:
=> Implement entrybox using GTK dialog

gtkwave3-gtk3/src/main.c
Resizing the window vertically did also resize the toolbar, which caused some vertical movement in all widgets below the toolbar.
=> Disable vexpand for toolbar

gtkwave3-gtk3/src/main.c, gtkwave3-gtk3/src/signal_list.c
This PR should fix the problem with the keybindings.
As far as I can tell the previous solution to this problem was to manually check if the focus was inside the `filter_entry` and ignore the accelerators in this case.
The method used in this PR should be more generic. It changes the order the key press events are handled to give widget `key-press-event` handlers priority over global accelerators. The code is based on the default implementation in GTK: https://gitlab.gnome.org/GNOME/gtk/-/blob/gtk-3-24/gtk/gtkwindow.c#L8244
=> Handle global accelerators after widget keybindings

gtkwave3-gtk3/configure.ac, gtkwave3-gtk3/src/tcl_helper.c
This PR exports the TCL commands in `gtkwave_commands` from the `gtkwave` namespace.
Without namespace: (This version is still supported after the changes in this PR)
```tcl
gtkwave::setMarker 128
gtkwave::setNamedMarker A 400 "Example Named Marker"
```
With namespace:
```tcl
namespace import gtkwave::*
setMarker 128
setNamedMarker A 400 "Example Named Marker"
```
This is especially useful to reduce typing when you use the `--wish` feature.
=> Export TCL commands in namespace

gtkwave3-gtk3/src/tcl_helper.c
This is a followup to #93. I didn't realize there was a separate initialization for the script TCL interpreter. These changes make it possible to also use `namespace import gtkwave::*` in scripts.
=> Also export TCL commands in GLOBALS->interp

.github/workflows/build.yml
The autotools were recently removed from the MSYS2 `base-devel` package (https://www.msys2.org/news/#2021-12-22-ongoing-cleanup-of-the-base-devel-package-group) which causes the CI build to fail.
=> Fix CI build after MSYS2 changes

gtkwave3-gtk3/src/helpers/fst/fstapi.c, gtkwave3/src/helpers/fst/fstapi.c
There's an existing fix in fstapi.c to set _IONBF on the FST file handle
on Windows and OS X.  This patch extends this to FreeBSD and OpenBSD
too, which both are otherwise unable to read FST files.
=> Use unbuffered I/O for FST on OpenBSD and FreeBSD

gtkwave3-gtk3/configure.ac, gtkwave3-gtk3/src/main.c, gtkwave3-gtk3/src/twinwave.c
I am porting gtkwave to build in macOS, and faced the following two issues.
First issue:
The GTK+3 built by Nix targets `broadway quartz` instead of only `quartz`, thus the target check is wrong:
```bash
_gdk_tgt=`$PKG_CONFIG --variable=target gdk-3.0`
if test "x$_gdk_tgt" = xquartz; then
```
```shell
$ pkg-config --variable=target gdk-3.0
$ pkg-config --variable=targets gdk-3.0
broadway quartz
```
The variable name is renamed to `targets` in newer version of GTK+3, and I modified the script to look up `quartz` in a loop.
Second issue:
The code uses GtkPlug and GtkSocket widgets. They are only available when GTK+3 is targeted to X11, according to [gtk+3 docs](https://docs.gtk.org/gtk3/class.Plug.html):
The GtkPlug and GtkSocket widgets are only available when GTK+ is compiled for the X11 …
=> Fix compilation under macOS for Nix

gtkwave3-gtk3/src/signal_list.c, gtkwave4/src/signal_list.c
This PR fixes a bug in `signal_list.c` where the drop highlight position is clamped to the total number of traces instead of the visible number of traces. This caused the highlight to potentially be draw below the last trace in the list, if closed groups were present.
=> Clamp drop position to number of visible traces

gtkwave3-gtk3/src/fst.c, gtkwave3/src/fst.c, gtkwave4/src/fst.c
The FST loader looks for signal names ending with [msb:lsb] or [bit] and if found parses that and removes it from the signal name. Previously it would always remove everything starting from the last '[' character, even if it did not match either pattern, e.g. with non-numeric text within brackets or with brackets in the middle of the signal name.
This patch changes the parsing code to a) check for the final closing ']' as last character in the name and b) check that no unexpected characters appear between the brackets. Only if the checks pass is the suffix parsed and removed from the signal name.
I have some use cases with yosys where I end up with multiple such signals that only differ in the part following the last '[', i.e. "foo[bar]" and "foo[baz]" which makes this particularly bad, …
=> FST loading fix for signals containing inner '[' characters

gtkwave3-gtk3/src/fst.c, gtkwave3/src/fst.c, gtkwave4/src/fst.c
A mismatched malloc_2/free_2 was causing memory
corruption when loading FST string signals. Change free to free_2 to free the correct address and not crash on these.
=> Don't crash when loading FST string sigs

gtkwave3-gtk3/contrib/bundle_for_osx/launcher.sh, gtkwave3/contrib/bundle_for_osx/launcher.sh, gtkwave4/contrib/bundle_for_osx/launcher.sh
Now works no matter what the current directory is allowing the binary to be run out of the application from the command line.
Note that I have only tested this by editing the script in the prebuilt application downloaded from https://sourceforge.net/projects/gtkwave/files/gtkwave-3.3.107-osx-app/ as I don't have the app build environment setup.
=> Improve bundle directory detection.

gtkwave3-gtk3/src/helpers/fst/fstapi.c, gtkwave3/src/helpers/fst/fstapi.c, gtkwave4/src/helpers/fst/fstapi.c
This is the same as OpenBSD and FreeBSD.
I tested the code in gtkwave3, gtkwave3-gtk3 and gtkwave4. I could only test that my change compiled in gtkwave4, but I was able to run the other versions of gtkwave and confirm that I can open FST files on NetBSD.
=> Disable stdio buffering when accessing FST files on NetBSD

gtkwave3-gtk3/src/gtk23compat.h, gtkwave3-gtk3/src/twinwave.c, gtkwave4/src/gtk23compat.h, gtkwave4/src/twinwave.c
Don't try to include gdk/gdkwayland.h unless the GDK backend declares support for Wayland. This allows Gtkwave to be built with Gtk versions
>= 3.22.26 without requiring Wayland support.
=> Only include Wayland headers when GDK has Wayland support

gtkwave3-gtk3/src/helpers/vzt_read.c, gtkwave4/src/helpers/vzt_read.c
Reading VZT files wasn't working with recent GCC versions, if at least optimization level 2 is used. The problem turned out to be related to `-fstrict-aliasing`, which caused the `pnt` variable in `vzt_rd_block_vch_decode` to not be advanced correctly. After modifying `vzt_rd_get_v32` and `vzt_rd_get_v64` to only use `unsigned char` types the problem seems to be fixed.
=> Fix VZT reader with -fstrict-aliasing

gtkwave3-gtk3/src/helpers/vzt_write.c, gtkwave4/src/helpers/vzt_write.c
The `use_multi_state` flag in `vzt_write.c` wasn't set in some cases, which caused `x` and `z` values to be written as incorrect `0`s and `1`s.  `use_multi_state` is a 1 bit unsigned integer and was only set if the LSB  of `s->chgx[i]` was set.
=> Fix use_multi_state condition in vzt_write.c

gtkwave3-gtk3/src/helpers/vzt_read.c, gtkwave4/src/helpers/vzt_read.c
If a string variable in a VZT file contains a value change at the beginning of the file it is displayed as `UNDEF` instead of the correct value. This PR changes the condition, which determines if `UNDEF` should be used. I'm not 100% sure that the new condition is correct, but it matches other similar conditions in the file and seems to work.
I've attached a test VZT file, if you want to replicate the problem: [vzt_with_strings.zip](https://github.com/gtkwave/gtkwave/files/10532356/vzt_with_strings.zip)
=> Fix reading strings at the start of a VZT file

gtkwave3-gtk3/src/globals.c, gtkwave3/src/globals.c, gtkwave4/src/globals.c
The gtkwave function caller is expecting to pass in the number of seconds.
This was causing MSYS2 builds to end up in a tight loop causing UI blocking and the cursor to be always busy.  This can easily be trigged during a reload and the underlying file or directory was removed, or the VCD is being rewritten by another process causing Win32 file locking.  Once triggered the only reliable exit is to kill the process.
Another consideration is to reevaluate the historical reason why this #ifdef exists at all, as a quick test compile today inside MSYS2 mingw-w64-x86_64-gcc shows that the POSIX sleep(unsigned int seconds) is implemented as expected by the gtkwave caller.
Reference:
https://learn.microsoft.com/en-us/search/?terms=sleep&scope=Desktop …
=> When using Sleep() on windows this API takes milliseconds

.github/workflows/build.yml
This should fix the build error on MSYS2:
configure: error: Couldn't find a usable gperf program.
Please install gperf which is available from
ftp://ftp.gnu.org/pub/gnu/gperf/
==> ERROR: A failure occurred in build().
Related links:
https://packages.msys2.org/base/mingw-w64-gperf
=> MSYS2 build.yml: install mingw-w64-${{ matrix.target.arch }}-gperf

gtkwave3-gtk3/src/helpers/fst/fstapi.c, gtkwave3/src/helpers/fst/fstapi.c, gtkwave4/src/helpers/fst/fstapi.c
AArch64 handles misaligned loads/stores in hardware.  In fact fstGetUint32 gets compiled into a plain load on -O2:
```
fstGetUint32:
ldr     w0, [x0]
ret
```
=> Define FST_DO_MISALIGNED_OPS on AArch64

gtkwave3-gtk3/src/helpers/fst/fstapi.c, gtkwave3/src/helpers/fst/fstapi.c, gtkwave4/src/helpers/fst/fstapi.c
This was reported by a user in nickg/nvc#596.  The FST writer emulates mmap on Windows by copying from the file to a temporary buffer and then flushing that buffer to disk in fstDestroyMmaps.  The problem here is that while `xc->curval_mem` is flushed, `xc->valpos_mem` is not.  One fix would be to duplicate the flushing logic for valpos_mem but it seems better to just use the native Windows MapViewOfFileEx API.  Cygwin has its own mmap emulation layer so the existing POSIX code should work fine there.
I've been using this patch for a while with no reported issues, and I did a full build of GtkWave on MSYS2 and checked it could load FST files created with it.
=> Use MapViewOfFileEx for mmap on Windows

.github/workflows/build.yml
This PR updates the Action used in CI job 'nightly'. By the way, the `workflow_dispatch` event is added, in order to allow manually triggering builds on forks.
=> ci: eine/tip was merged into pyTooling/Actions/releaser

CHANGELOG.md, ChangeLog.old
This PR converts the changelog for version 3.4 to markdown or, more specifically, this format: https://keepachangelog.com/en/1.1.0/
Using markdown has the advantage that it can be viewed in a more readable form on GitHub (https://github.com/rfuest/gtkwave/blob/changelog/CHANGELOG.md), without much impact on the readability of the raw text version. And the markdown can easily be copied as the release notes for the GitHub releases.
=> Convert 3.4 changelog to markdown

share/appdata/gtkwave.appdata.xml
According to `LICENSE.TXT` and the individual file headers the license is "... either version 2 of the License, or (at your option)
any later version." I think that means that the SPDX identifier in the appdata is incorrect, but I'm not very familiar with the intricacies of open source licensing.
=> Change project license in appdata

meson.build, src/gw-time-display.c, src/wave_view.c
This PR fixes an issue on some distributions, where `bzip2` couldn't be located by meson. It also enables some GLib macros to ensure that the code keeps compatible with our minimum required GLib version.
I did choose Ubuntu 20.04 LTS as the oldest version that should be supported by GTKWave 3.4. In my opinion a 3.5 year old target is a good compromise between supporting older distros and not being limited by having to support older library versions. Users on even older versions can still use GTKWave 3.3 (LTS) or the Flatpak version.
=> Fix build in Ubuntu 20.04

CHANGELOG.md, examples/gtkwaverc, man/gtkwaverc.5, src/ae2.c, src/analyzer.c, src/bitvec.c, src/extload.c, src/fst.c, src/ghw.c, src/globals.c, src/globals.h, src/lx2.c, src/lxt.c, src/main.c, src/rc.c, src/rc.h, src/search.c, src/symbol.c, src/symbol.h, src/vcd.c, src/vcd.h, src/vcd_partial.c, src/vcd_recoder.c, src/vzt.c
This PR removes an old unused ifdef, a global variable, and two rc variables. All of them were previously discussed in different issues and they should all be obsolete and safe to remove.
=> Remove old ifdefs and rcvars

CHANGELOG.md, man/gtkwaverc.5, src/globals.c, src/globals.h, src/menu.c, src/rc.c
This PR removes the hard coded support for gedit. Instead GTKWave will fall back to use the default editor that is associated with the source file type. This isn't as good as the hard coded gedit support, because there is no generic way of opening a text file at a specific line, but at least the right source file will be opened.
A new rc variable can now be used to run editors in a separate terminal, which makes it possible to use text mode editors even if GTKWave itself wasn't run from a terminal.
The new code should now also work on Windows, but I haven't tested that yet.
=> Remove dependency on gedit

src/treesearch.c
This PR fixes building of GTKWave with clang.
=> Fix pointer casting build error using clang

src/globals.h
This PR changes the type of `GLOBALS->preg_regex_c_1` to fix issues in Windows and macOS. All functions that uses this variable expect `regex_t` as an argument and it also allocated to a size of `sizeof(regex_t)`.
=> Change type of GLOBALS->preg_regex_c_1

src/gw-wave-view.c
Currently when gtk_widget_get_scale_factor() was !=1 crated surface is not sufficient size, which leads to only 1/scale^2 of the waveview being visible.
I've reproduced it on Linux and MacOS. This patch fixed it on both.
=> Fix waveview scaling issue when on HiDPI displays

src/menu.c
gdk_pixbuf_get_from_window is scale aware, but cairo_image_surface_create is not.
There are some calls to cairo_image_surface_create in mousover, but I'm not familiar with the project yet to know if those are also affected.
=> Fix "grab to file" on HiDPI displays

lib/libgtkwave/src/gw-color.c
Older GCC versions (< version 13) didn't like the casts inside the code generated by the `X11_CONST` macro.
=> Fix compilation on older GCC versions

lib/libgtkwave/src/gtkwave.h, lib/libgtkwave/src/gw-stems.c, lib/libgtkwave/src/gw-stems.h, lib/libgtkwave/src/meson.build, lib/libgtkwave/test/gw-stems.c, lib/libgtkwave/test/meson.build, src/fst.c, src/globals.c, src/globals.h, src/menu.c
This PR moves the extracts the code that handles stems from the FST loader into a new `GwStems` class in libgtkwave.
=> Add GwStems to libgtkwave

lib/libgtkwave/src/gtkwave.h, lib/libgtkwave/src/gw-blackout-regions.c, lib/libgtkwave/src/gw-blackout-regions.h, lib/libgtkwave/src/meson.build, lib/libgtkwave/test/gw-blackout-regions.c, lib/libgtkwave/test/meson.build, src/currenttime.h, src/fst.c, src/globals.c, src/globals.h, src/gw-time-display.c, src/gw-wave-view.c, src/vcd_partial.c, src/vcd_recoder.c
This PR adds a new GwBlackoutRegions object to manage blackout regions in FST and VCD files.
=> Add GwBlackoutRegions to libgtkwave

src/fst.c, src/fst.h, src/ghw.c, src/globals.c, src/globals.h, src/lx2.c, src/main.c, src/menu.c, src/tcl_commands.c, src/treesearch.c, src/vcd.h, src/vcd_partial.c, src/vcd_recoder.c
This PR moves the global variables that belong to the dump file loaders into structs in preparation for further refactoring and for moving the loaders into libgtkwave. Each loader uses two objects, one to store all variables that are only used during the initial loading and another that is kept for the runtime of the session. The second object contains all information that is necessary for the `import_XXX_trace` methods.
=> Use structs for dump file loader state

meson.build, meson_options.txt, src/helpers/meson.build, src/meson.build
This PR changes the build system to set the rpath for executables if the prefix is not `/usr` or if the feature is enabled manually.
=> Set rpath for executables

lib/libghw/libghw.c, lib/libghw/libghw.h
This updates libghw to the upstream from https://github.com/ghdl/ghdl. The main change is skipping a linear search in `ghw_read_cycle_cont`, if this is possible. In my testing this provided a massive speedup. With this change, loading the ghw file from https://github.com/gtkwave/gtkwave/issues/280#issuecomment-1791391127 took about 20s instead of more than 6 minutes before. The file consumes about 29 GB of RAM, and behaves quite strangely (e.g., signals change name after inserting them to the wave window). So there may still be some bugs left, but the results from the two implementations of `ghw_read_cycle_cont` matched (tested with an assert for a few different log files).
Includes the following changes:
- https://github.com/ghdl/ghdl/pull/1825
- https://github.com/ghdl/ghdl/pull/1807
- …
=> libghw - Update to latest upstream version, speedup

gtkwave3/src/ghw.c, gtkwave3/src/globals.c, gtkwave3/src/globals.h, gtkwave3/src/libghw.c, gtkwave3/src/libghw.h
Changes:
- Update libghw to upstream as of 2024-01-18
- Update libghw with memory access checks
- Add memory access checks to ghw:
* Incorrect union casts
* Out-of-bounds access in GLOBALS->nxp_ghw_c_1 (add GLOBALS->nbr_sigs_ghw_c_1 to check this)
* Incrementing *sig beyond GHW_NO_SIG
* NULL hierarchy
=> GHW - (LTS) Add checks to prevent memory access issues when loading ghw files

contrib/rtlbrowse/stem_recurse.c, src/main.c, src/twinwave.c
I was working on `rtlbrowse` and noticed the return value of shmat was being incorrectly handled
The current implementation cause seg fault with command  `rtlbrowse 0a123`  (or any hexadecimal digits that do not represent a valid shared memory ID)
According to POSIX 2008 and [man page](https://linux.die.net/man/2/shmat) of shmat
shmat will return (void *) -1 upon failure, not 0
I also corrected this issue for  other shmat in the code base.  
Although `MapViewOfFile` does return 0 upon failure. It already got its own error handler wrapped in `ifdef __MINGW32__`
=> Correctly handle the return value of shmat

share/io.github.gtkwave.GTKWave.metainfo.xml
According to the new [guidelines on flathub](https://docs.flathub.org/docs/for-app-authors/linter/#appstream-failed-validation),
> All graphical applications having a desktop file must have this tag in the MetaInfo.
Currently, all flatpak builds at https://github.com/flathub/io.github.gtkwave.GTKWave are failing due to this in the Validate Build step.
=> flatpak: add launchable tag in metainfo

lib/libgtkwave/src/meson.build
Setting the `introspection` variable to `false` did cause an build error because of an undefined variable.
=> Fix build without GObject introspection

src/signal_list.c
Fixes an issue that was reported in #322, where the waveform highlight isn't updated correctly.
=> Redraw waveform highlight when trace selection changes

src/ptranslate.c, src/ttranslate.c
Previously, if the executable file was not found, the `cmd` pointer would not be properly released, leading to a memory leak.
`// I also recommend adding a popup notification when the executable file is not found. This would reduce confusion for users. However I'm not sure how to notifications get popped in gtkwave. 
`
=> Fix memory leak in filter loads

.github/workflows/build.yml, .github/workflows/ci.yml
Get rid of the warnings about Node.js 16 actions being deprecated: https://github.com/gtkwave/gtkwave/actions/runs/8896945005
=> [CI] bump actions/checkout to v4

.github/workflows/ci.yml
This PR fixes the Linux CI build by running `apt-get update` before installing the dependencies.
=> Run 'apt-get update' in Linux CI

.github/workflows/gh-page.yml, docs/conf.py
I noticed that the PR #338 hasn't been updated in a while.
This PR implements the same GitHub action as #338 but uses the new recommended way of publishing to GitHub Pages.
=> Add GitHub Action workflow 'docs' using new recommended way 

lib/libgtkwave/src/meson.build
This PR should fix a dependency issue when libgtkwave is built, which sometimes caused the build to fail.
=> Fix gw-enums.h build dependency in libgtkwave

src/fgetdynamic.c
When reading DOS format files. "AB[_CR_][_LF_]CD" should break to "AB" and "CD"  not  "AB" and "[_LF_]CD". 
The later one will mess up many function including `read_save_helper` .
`continue` must be added or leading [_LF_](or [_CR_]) will be incorrectly appended to the start of `line`
=> Fix leading [LF] skipping issue

lib/libgtkwave/src/gw-fst-loader.c, lib/libgtkwave/src/gw-vcd-loader.c, lib/liblxt/lxt2_read.h, lib/libvzt/vzt_read.h, src/file.c, src/globals.c, src/globals.h, src/main.c, src/tcl_np.c
This PR fix several compiling errors on Windows ( both Cygwin and MSYS2)
Since MSVC supports %lld and int64_t starting from Visual Studio 2015, the use of __int64 in headers is no longer necessary.
Note: libglib in Cygwin is unmaintained and is not fully compatible with GCC version 11 or later.
=> Fix Windows Build Issues

lib/libfst/fstapi.c
This is a mistake introduced by my earlier PR #191. On 32-bit Windows `size_t` is a 32-bit type so shifting by 32 or more places is undefined behaviour. Avoid this by casting to `DWORD64` first.
=> Fix undefined behaviour in fstMmap2 on 32-bit Windows

meson.build
This PR bumps the GLib dependency to require at least version 2.72 to give access to some functions that were added between 2.64 and 2.72. This version of GLib the latest version that is available in Ubuntu 22.04 LTS, which is the first LTS version of Ubuntu which includes GTK 4. We might later tweak this requirement up or down a bit, depending on which minimum GTK 4 we want to support.
=> Bump GLib dependency to 2.72

src/main.c
In the CreateProcess function, the first parameter `lpApplicationName` does not use the search path, as documented in the [WINAPI Doc](https://learn.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-createprocessa#parameters).
The second parameter `lpCommandLine` uses the search path if `lpApplicationName` is NULL.
Tested on msys running on windows 11. 
However, due to Microsoft's removal of older documentation, I am uncertain whether this change might impact previous versions of Windows. Please let me know if I should setup such environment and test it.
=> Fix: Failed to create rtlbrowse subprocess on windows

lib/libfst/fstapi.c
This was reported by a couple of users in nickg/nvc#637. The `fstReaderOpen` function cannot open any FST files when linked against the Windows [Universal C Runtime](https://learn.microsoft.com/en-us/cpp/windows/universal-crt-deployment?view=msvc-170), the modern replacement for MSVC.
The problem is that the file position of the `zfd` file descriptor passed to `gzdopen` is 18 instead of the expected 17. I'm unsure if this is a bug or not but the behaviour can be seen easily with the following program:
```c
#include <stdio.h>
#include <fcntl.h>
#ifdef __MINGW32__
#include <io.h>
#else
#include <unistd.h>
int _tell(int fd)
{
return lseek(fd, 0, SEEK_CUR);
}
#endif
int main(int argc, char **argv)
{
FILE *f = fopen(argv[1], "rb");
setvbuf(f, NULL, _IONBF, 0);
char ch = fgetc(f); …
```
=> Fix fstReaderOpen failure with Windows UCRT runtime library

lib/libfst/fstapi.c
`secnum` is only used when `FST_DEBUG` is defined.
=> Fix unused variable warning in fstReaderGetValueFromHandleAtTime

lib/libfst/fstapi.c
This fixes Clang 18 (default clang version in Ubuntu 24.04) compiler errors.
```
gtkwave/fstapi.c:554:19: error: variable length arrays in C++ are a Clang extension [-Werror,-Wvla-cxx-extension]
554 | unsigned char buf[chk_len];
|                   ^~~~~~~
gtkwave/fstapi.c:554:19: note: read of non-const variable 'chk_len' is not allowed in a constant expression
gtkwave/fstapi.c:553:5: note: declared here
553 | int chk_len = 5; /* TALOS-2023-1783 */
|     ^
```
=> Fix Ubuntu 24.04/clang 18.0 warning on chk_len

gtkwave3-gtk3/share/appdata/io.github.gtkwave.GTKWave.metainfo.xml, gtkwave3/share/appdata/io.github.gtkwave.GTKWave.metainfo.xml
They cause metainfo validation to fail.
Looks like a copy-and-paste issue.
=> Fix duplicate 'releases' tags in metainfo

gtkwave3-gtk3/configure, gtkwave3-gtk3/configure.ac, gtkwave3-gtk3/src/main.c, gtkwave3-gtk3/src/twinwave.c
Currently, the lts version cannot be built on macOS if gtk3 is used.
GtkSocket and GtkPlug are not available on macOS.  I backported a change from master branch to fix it.
In addition, the configure script cannot detect the quartz target of gdk because the variable name of pkg-config is changed.
It should be `targets` rather than `target`.  This pull request also fixes that.
=> LTS: Fix building on macOS with gtk3

lib/libfst/CMakeLists.txt, lib/libfst/fstapi.c
This pr contributes a few quality-of-life improvements that I have come across. It fixes a stringop-overread warning issued by the C compiler at build and sets the minimum cmake version to a non-deprecated version.
When building `libfst` from the `lib` directory I use the following command:
cmake --DCMAKE_C_FLAGS="-O3 -Wall -Wextra -pedantic" -Hlibfst -Blibfst
cmake --build libfst --target all
This produces the following warning:
In function ‘fstWritex’,
inlined from ‘fstReaderIterBlocks2.part.0’ at /tmp/build-via-sdist-b4bq_3__/pylibfst-0.2.1.dev0/fst/fstapi.c:5903:41:
/tmp/build-via-sdist-b4bq_3__/pylibfst-0.2.1.dev0/fst/fstapi.c:3468:21: warning: ‘write’ reading between 65536 and 2147483647 bytes from a region of size 16 [-Wstringop-overread]
3468 |                 if …
=> fix stringop-overread warning

lib/libfst/fstapi.c, lib/libghw/libghw.c, lib/libgtkwave/src/gw-vcd-file.h, lib/libvzt/vzt_read.c
This pr fixes an issue where a negative number is left-shifted in ghw, an implicit cast from a signed to an unsigned data type in vzt and improves upon an earlier fix that introduced a limit in the size of an id string in fst.
The left-shift of a negative number causes a warning in ghw.
Compiling gtkwave produces the following warning:
../lib/libghw/libghw.c:276:25: warning: left shift of negative value [-Wshift-negative-value]
276 |             r |= r_mask << off;
|                  ~~~~~~~^~~~~~
The fix creates the mask not by shifting in zeros into a one-vector from the right but by shifting in ones into a zero-vector from the right and then negating.
An implicit cast from a signed char pointer to an unsigned char pointer causes a warning in vzt.
Compiling gtkwave produces the …
=> fix left-shift and signedness warnings

lib/libgtkwave/doc/meson.build, lib/libgtkwave/src/meson.build
The changes in https://github.com/gtkwave/gtkwave/commit/254cf5c835ad4d638d51e4d76643a2329fb12ebc had broken the build of the libgtkwave docs.
=> Fix building of libgtkwave docs

gtkwave3-gtk3/src/gtk23compat.h, gtkwave3-gtk3/src/tcl_helper.h
gcc 15 strengthens the incompatible pointer type checks, particularly in respect of function pointers, where the types of arguments passed to the function are also now significant.
This change fixes one such case in `tcl_helper.h` and works around the other by using a typecast in `gtk23compat.h`, since the function argument types are not identical in all cases there.
I don't think this is likely to cause breakage with older compilers but the oldest I tried it with is gcc 9.3.1 and I didn't try any non-gcc compilers. I also didn't update the gtk2 codebase (would anybody be using a mix of that and gcc 15?).
=> Port to gcc 15

gtkwave3-gtk3/src/tcl_commands.c, gtkwave3-gtk3/src/tcl_helper.c, gtkwave3-gtk3/src/tcl_np.c
1. `CONST` no longer defined in `tcl.h`
This was a helper for non ANSI-C compilers, replaced by `const` going forwards.
2. ` Tcl_FindExecutable` now returns `const char *` rather than `void`
See https://www.tcl-lang.org/man/tcl9.0/TclLib/FindExec.html
I only applied the changes in the gtk3 version; would anybody be using gtk2 and tcl9?
=> Fixes for tcl9 compatibility

lib/libghw/libghw.c
@tbybell: This should also be applied to LTS, see https://github.com/ghdl/ghdl/pull/2968 for more information.
=> Update libghw to latest upstream
